### ISSUE TITLE
under windows it need --model?

### ISSUE THREAD

**Issue by lafaty80** [odedlaz/ax3600-files#7]
Hi,

I use this method and tool under windows 10. When I copy the img file into the scripts folder and run this script I get error message:

**header.py modify --country CN bdata_mtd9.img bdata_mtd9.img.modified**

_usage: header.py modify [-h] [--country COUNTRY] --model MODEL [--test] SRC DST
header.py modify: error: the following arguments are required: --model_

If I add --model AX3600 argument I get this:

**header.py modify --country CN --model AX3600 bdata_mtd9.img bdata_mtd9.img.modified**

_Traceback (most recent call last):
  File "d:\xiaomi\ax3600-files-master2\scripts\header.py", line 158, in <module>
    if args.command == Commands.Extract.describe():
NameError: name 'Commands' is not defined_

I use python 3.6.

What do you think I'm doing wrong?

Thanks your help.

Regards,
lafaty

**Comment by Coenenp** [comment]
@lafaty80 looks like you didn't specify how to fix the issue. The script should not have the final 's'. Command.Extract.describe() instead of Command**_s_**.Extract.describe()

    if args.command == Command.Extract.describe():
        extract_command(args.path)

    if args.command == Command.Modify.describe():
